---
swagger: '2.0'
info:
  title: git data source
  version: '1.0'
  description: git data source V2
paths:    # swagger forces me to add at least one path
  /noop:
    get:
      description: no-op
      responses:
        200:
          description: ok
definitions:
  DataSource:
    type: object
    properties:
      Slug:
        type: string
        example: git
      Name:
        type: string
        example: git
  MetaData:
    type: object
    properties:
      BackendName:
        type: string
        example: insights-datasource-git
      BackendVersion:
        type: string
        example: v0.1.0
      Project:
        type: string
        example: DevStats
      Tags:
        type: array
        items:
          type: string
          example: my-tag
  Identity:
    type: object
    properties:
      Id:
        type: string
        example: 1234567890abcdef
        description: PK - up to 50 chars
      Name:
        type: string
        example: Lukasz Gryglicki
      Username:
        type: string
        example: lgryglicki
        description: but git doesn't have it, so it will be empty
      DataSourceId:
        type: string
        example: git
        description: data source type slug (FK)
  CommitFileAction:
    type: object
    properties:
      Name:
        type: string
        example: git.yaml
      Action:
        type: string
        example: a
      Added:
        type: integer
        x-nullable: true
        example: 6
      Removed:
        type: integer
        x-nullable: true
        example: 4
      Changed:
        type: integer
        x-nullable: true
        example: 10
  CommitRole:
    type: object
    properties:
      Id:
        type: string
        example: 1234567890abcdef
        description: PK - up to 50 chars
      Weight:
        type: integer
        description: this is by default 1, so if there is an author and a committer each role have 1/(1+1) = 50% of commit
        example: 1
      Name:
        type: string
        example: author, committer, signer, co-author, tester, approver, reviewer, reporter, informer, resolver, influencer
      When:
        type: string
        format: date-time
      WhenInTz:
        type: string
        format: date-time
      WhenTz:
        type: number
        example: -2.5
      User:
        type: object
        $ref: "#/definitions/Identity"
  CommitStats:
    type: object
    properties:
      LinesAdded:
        type: integer
        example: 10
      LinesRemoved:
        type: integer
        example: 5
      LinesChanged:
        type: integer
        example: 15
  Commit:
    type: object
    properties:
      Id:
        type: string
        example: 1234567890abcdef
        description: PK - up to 50 chars
      DataSourceId:
        type: string
        example: git
        description: data source type slug (FK)
      SHA:
        type: string
        example: 2b20505d9d60202c6779342033d344dba0685d1b
      HashShort:
        type: string
        example: 2b20505d9d60202c6779342033d344dba0685d1b
      RepositoryURL:
        type: string
        example: https://github.com/cncf/devstats
      Message:
        type: string
        x-nullable: true
        example: my commit body
      Title:
        type: string
        x-nullable: true
        example: fix-the-bug
      CommitURL:
        type: string
        example: https://github.com/cncf/devstats/commit/2a667b1d4c3462300382eba80ae89bf8e9dc0e5c
      RepositoryShortURL:
        type: string
        example: devstats
      RepositoryType:
        type: string
        example: github, gerrit, gitlab, bitbucket
      IsSquashed:
        type: boolean
        example: true
      IsDoc:
        type: boolean
        example: true
      IsEmpty:
        type: boolean
        example: true
      Parents:
        type: array
        items:
          type: string
          description: commit parents SHAs
          example: 2b20505d9d60202c6779342033d344dba0685d1b
      Stats:
        type: object
        $ref: "#/definitions/CommitStats"
      Files:
        type: array
        items:
          $ref: "#/definitions/CommitFileAction"
      Roles:
        type: array
        items:
          $ref: "#/definitions/CommitRole"
  LanguageStats:
    type: object
    properties:
      Language:
        type: string
        example: golang
      CalculatedAt:
        type: string
        format: date-time
      Files:
        type: integer
        example: 6
      Blank:
        type: integer
        example: 10
      Comment:
        type: integer
        example: 15
      Code:
        type: integer
        example: 260
  RepositoryStats:
    type: object
    properties:
      RepositoryURL:
        type: string
        example: https://github.com/cncf/devstats
      CalculatedAt:
        type: string
        format: date-time
      TotalLinesOfCode:
        type: integer
        example: 65535
      ProgrammingLanguagesStats:
        type: array
        items:
          $ref: "#/definitions/LanguageStats"
  Event:
    type: object
    description: single event in git is a commit, it commit trailers/roles (at least author & committer), stats are per repo (programming language summary and LOC SUMMARY)
    properties:
      Commit:
        type: object
        $ref: "#/definitions/Commit"
  Data:
    type: object
    description: this is the final output of insights-datasource-git, data source will output packs up to some fixed size, like 500 events pack at once
    properties:
      DataSource:
        type: object
        $ref: "#/definitions/DataSource"
      MetaData:
        type: object
        $ref: "#/definitions/MetaData"
      Endpoint:
        type: string
        description: git endpoint for which data is being sent
        example: https://github.com/cncf/devstats
      RepositoryStats:
        type: object
        $ref: "#/definitions/RepositoryStats"
      Events:
        type: array
        items:
          $ref: "#/definitions/Event"
