---
swagger: '2.0'
info:
  title: RocketChat data source
  version: '1.0'
  description: RocketChat data source V2
paths:    # swagger forces me to add at least one path
  /noop:
    get:
      description: no-op
      responses:
        200:
          description: ok
definitions:
  DataSource:
    type: object
    properties:
      Slug:
        type: string
        example: rocketchat
      Name:
        type: string
        example: RocketChat
  MetaData:
    type: object
    properties:
      BackendName:
        type: string
        example: insights-datasource-rocketchat
      BackendVersion:
        type: string
        example: v0.1.0
      Project:
        type: string
        example: Hyperledger Sawtooth
      Tags:
        type: array
        items:
          type: string
          example: my-tag
  Identity:
    type: object
    properties:
      Id:
        type: string
        example: 1234567890abcdef
        description: PK - up to 50 chars
      Name:
        type: string
        example: Lukasz Gryglicki
      Username:
        type: string
        example: lgryglicki
      DataSourceId:
        type: string
        example: rocketchat
        description: data source type slug (FK)
  Channel:
    type: object
    properties:
      InternalId:
        type: string
        example: 1234567890abcdef
        description: RocketChat internal chat channel ID
      Name:
        type: string
        example: Channel name
      Slug:
        type: string
        description: RocketChat endpoint contain two values server URL and channel name, so we need to concatename them with space (not allowed in URL)
        example: 'https://chat.hyperledger.org sawtooth'
      Topic:
        type: string
        example: Channel topic
      MemberCount:
        type: integer
        description: this looks like a compute field - do we really need it? We can calculate this from RDS.
        example: 10
      MessageCount:
        type: integer
        description: this looks like a compute field - do we really need it? We can calculate this from RDS.
        example: 10
      CreatedAt:
        type: string
        format: date-time
        example: '2019-09-02 03:00:33.000000'
      UpdatedAt:
        type: string
        format: date-time
        description: this looks like a compute field - do we really need it? We can calculate this from RDS.
        example: '2019-09-02 03:00:33.000000'
  MessageReaction:
    type: object
    properties:
      Type:
        type: string
        example: ok
        description: literal reaction type
      Emoji:
        type: string
        example: 😃
        description: UNICODE emoji data
      Author:
        type: object
        $ref: "#/definitions/Identity"
  MessageActivity:
    type: object
    properties:
      Id:
        type: string
        example: 1234567890abcdef
        description: PK - up to 50 chars
      MessageId:
        type: string
        example: 1234567890abcdef
        description: FK - up to 50 chars
      MessageInternalId:
        type: string
        example: 107625428
        description: RocketChat message internal id - can be any string
      ParentId:
        type: string
        x-nullable: true
        example: 1234567890abcdef
        description: parent message FK - up to 50 chars
      ParentInternalId:
        type: string
        x-nullable: true
        example: 107625428
        description: RocketChat parent message internal id - can be any string
      CreatedAt:
        type: string
        format: date-time
        example: '2019-09-02 03:00:33.000000'
      ActivityType:
        type: string
        example: rocketchat_message_created, rocketchat_message_edited, rocketchat_message_reaction, rocketchat_message_mention, rocketchat_attachment_added, rocketchat_attachment_edited
        description: allows reconstructing relations
      Body:
        type: string
        description: message, reply, body, file name
        example: My comment body
        x-nullable: true
      Identity:
        type: object
        description: activity creator (ProjectDataSourceIdentity)
        $ref: "#/definitions/Identity"
      Reaction:
        type: object
        x-nullable: true
        $ref: "#/definitions/MessageReaction"
  Message:
    type: object
    properties:
      Id:
        type: string
        example: 1234567890abcdef
        description: PK - up to 50 chars
      InternalId:
        type: string
        example: 107625428
        description: RocketChat internal id - can be any string
      CreatedAt:
        type: string
        format: date-time
      URLs:
        type: array
        items:
          type: string
          example: https://msg-url
      Type:
        type: string
        example: ok
        description: can be message, attachment
      Channel:
        type: object
        $ref: "#/definitions/Channel"
      Activities:
        type: array
        items:
          $ref: "#/definitions/MessageActivity"
  Event:
    type: object
    description: single event in RocketChat is a message, it contains neted activities for that message
    properties:
      Message:
        type: object
        $ref: "#/definitions/Message"
  Data:
    type: object
    description: this is the final output of insights-datasource-rocketchat, data source will output packs up to some fixed size, like 500 events pack at once
    properties:
      DataSource:
        type: object
        $ref: "#/definitions/DataSource"
      MetaData:
        type: object
        $ref: "#/definitions/MetaData"
      Endpoint:
        type: object
        description: RocketChat endpoint for which data is being sent
        properties:
          RocketChatServer:
            type: string
            example: https://chat.hyperledger.org
          RocketChatChannel:
            type: string
            example: sawtooth
      Events:
        type: array
        items:
          $ref: "#/definitions/Event"
